{
    "name": "Nena Record",
    "summary": "Módulo custom que contiene la información del Expediente",
    "author": "Droguería Nena, C.A.",
    "category": "Dronena",
    "version": "18.0.0.0.1",
    "application": True,
    "depends": [
        "base",
        "mail",
        "contacts",
        "accountant",
        "nena_partner_config_record",
        "nena_localization_partners",
        "nena_commercial_structure",
        "l10n_ve_ut"
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/res_groups.xml",
        "data/nena.chain.csv",
        "data/nena.person.type.csv",
        "data/account.payment.term.csv",
        "views/res_partner.xml",
        "views/record.xml",
        "views/group.xml",
        "views/chain.xml",
        "views/chain_credit_conditions.xml",
        "views/client_credit_conditions.xml",
        "views/credit_conditions.xml",
        "views/regent.xml",
        "views/postulation_monitor.xml",
        "views/person_type.xml",
        #"views/account_payment_term.xml",
        "views/menuitem.xml",
        "views/menu_res_partner.xml",
    ],
}