{
    "name": "Nena Record",
    "summary": "Módulo custom que contiene la información del Expediente",
    "author": "Dronena",
    "category": "Record",
    "version": "18.0.0.0.1",
    "application": True,
    "depends": [
        "base",
        "mail",
        "contacts",
        "nena_partner_config_record",
        "nena_localization_partners",
        "l10n_ve_ut"
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/nena.region.csv",
        "data/nena.district.csv",
        "data/nena.zone.csv",
        "views/record.xml",
        "views/group.xml",
        "views/chain.xml",
        "views/commercial_structure.xml",
        "views/chain_credit_conditions.xml",
        "views/client_credit_conditions.xml",
        "views/credit_conditions.xml",
        #"views/partner_views.xml",
        "views/menuitem.xml",
    ],
}
