{
    "name": "Nena General Parameter",
    "summary": "Parametros Generales del Sistema",
    "author": "Droguería Nena, C.A.",
    "category": "Dronena",
    "version": "18.0.0.0.1",
    "depends": ["base"],
    "data": [
        "security/res_groups.xml",
        "security/ir.model.access.csv",
        "data/nena.postulation.type.csv",
        "data/nena.type.identification.csv",
        "data/nena.regulatory.entity.csv",
        "data/nena.region.csv",
        "data/nena.district.csv",
        "data/nena.zone.csv",
        "data/nena.person.type.csv",
        "views/menuitem.xml",
        "views/nena_postulation_type.xml",
        "views/nena_type_identification.xml",
        "views/nena_regulatory_entity.xml",
        "views/nena_gen_status.xml",
        "views/nena_commercial_structure.xml",
        "views/nena_person_type.xml",
    ],
    "application": True,
    "license": "LGPL-3",
}