from . import postulation_type
from . import product_type
from . import supplier_type
from . import regulatory_entity
from . import document_type
from . import partner_config_record
from . import nena_gen_status 
from . import nena_cause_status
from . import nena_condition
from . import nena_gen_management
from . import nena_customer_clasification
from . import nena_customer_category
from . import nena_payment_type
from . import nena_document_type
from . import hr_job
from . import document_approver
from . import nena_commercial_activity