{
    "name": "Nena General",
    "summary": "Módulo custom que contiene los modelos de uso General del Sistema",
    "author": "Droguería Nena, C.A.",
    "category": "Dronena",
    "version": "18.0.0.0.1",
    "application": False,
    "depends": ["base"],
    "data": [
        "security/ir.model.access.csv",
        "data/nena.gen.management.csv",
        "data/nena.gen.status.csv",
        "data/nena.cause.status.csv",
        "data/nena.condition.csv",
        "data/nena.region.csv",
        "data/nena.district.csv",
        "data/nena.zone.csv",
        "data/nena.document.type.csv",
        "views/gen_management.xml",
        "views/gen_status.xml",
        "views/cause_status.xml",
        "views/condition.xml",
        "views/commercial_structure.xml",
        "views/document_type.xml",
    ],
}