{
    "name": "Nena Partner Config Record",
    "summary": "Módulo custom que contiene las configuraciones necesarias para gestionar postulaciones",
    "description": """
    * Configuración base para gestion de permisos y documentos que se solicitan a los postulantes""",
    "author": "Droguería Nena, C.A.",
    "category": "Dronena",
    "version": "18.0.0.0.3",
    "application": True,
    "depends": [
        "base",
        "contacts",
        "stock",
        "hr"],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "data/postulation.type.csv",
        "data/nena.gen.management.csv",
        "data/nena.gen.status.csv",
        "data/nena.cause.status.csv",
        "data/nena.condition.csv",
        "data/nena.customer.clasification.csv",
        "data/nena.customer.category.csv",
        "data/regulatory.entity.csv",
        "data/nena.payment.type.csv",
        "data/nena.document.type.csv",
        "data/nena.commercial.activity.csv",
        "views/postulation_type.xml",
        "views/supplier_type.xml",
        "views/product_type.xml",
        "views/document_type.xml",
        "views/partner_config_record.xml",
        "views/gen_management.xml",
        "views/gen_status.xml",
        "views/condition.xml",
        "views/cause_status.xml",
        "views/customer_clasification.xml",
        "views/customer_category.xml",
        "views/payment_type.xml",
        "views/nena_document_type.xml",
        "views/commercial_activity.xml",
        "views/menuitem.xml",
        "views/hr_job.xml",
    ],
}