{
    "name": "Nena Partner Config Record",
    "summary": "Módulo custom que contiene las configuraciones necesarias para gestionar postulaciones",
    "description": """
    * Configuración base para gestion de permisos y documentos que se solicitan a los postulantes
    """,
    "author": "Droguería Nena, C.A.",
    "category": "Uncategorized",
    "version": "18.0.0.0.3",
    "application": True,
    "depends": ["base","contacts","tipo_productos"],
    "data": [
        "security/ir.model.access.csv",
        "data/postulation.type.csv",
        "data/nena.gen.status.csv",
        "data/nena.cause.status.csv",
        "data/nena.condition.category.csv",
        "data/nena.condition.csv",
        "data/nena.client.clasification.csv",
        "data/nena.customer.category.csv",
        "data/nena.payment.type.csv",
        "data/nena.document.type.csv",
        "views/postulation_type.xml",
        "views/customer_type.xml",
        "views/supplier_type.xml",
        "views/product_type.xml",
        "views/document_type.xml",
        "views/partner_config_record.xml",
        "views/gen_status.xml",
        "views/condition.xml",
        "views/cause_status.xml",
        "views/client_clasification.xml",
        "views/customer_category.xml",
        "views/payment_type.xml",
        "views/nena_document_type.xml",
        "views/menuitem.xml",
    ],
}