from . import res_partner 
from . import nena_record
from . import nena_group
from . import nena_chain
from . import nena_postulation_monitor
from . import nena_credit_conditions_chain
from . import nena_credit_conditions_customer
from . import nena_document_type
from . import nena_document_approver
from . import nena_document_approver_line
from . import nena_attachment_line
from . import nena_record_config